#!/bin/sh

myspeakdir="$HOME/.my-speak"
lockfilepath="$myspeakdir/lock"
pidfilepath="$myspeakdir/pid"
pipefile="$myspeakdir/text_named_pipe"
speakngpath="$(which speak-ng)"

mkdir -p "$myspeakdir"
mkfifo --mode=600 "$pipefile"

xsel -p | tr '\n' ' ' > "$pipefile" &

daemonize -l "$lockfilepath" -p "$pidfilepath" "$speakngpath" -f "$pipefile"
